/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Filtro;

import ClassesDeConexao.EquipeDB;
import ClassesDeConexao.ItemCobrancaDB;
import ClassesDeConexao.ServicosAExecutarDB;
import Contantes.Procedures;
import Model.Bairros;
import Model.Status;
import Util.UtilSql;
import Util.Utilidades;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import view.Gestao.GestaoOrdemServico;

/**
 *
 * @author csqueiroz
 */
public class FiltroGestaoOrdemServico extends javax.swing.JPanel {

    private GestaoOrdemServico gestaoOrdemServico;
    private HashMap parametros = new HashMap();
    private HashMap restricoesGeral = new HashMap();
    private ArrayList<HashMap> retorno = new ArrayList();

    /**
     * Creates new form FiltroGestaoOrdemServico
     */
    public FiltroGestaoOrdemServico(GestaoOrdemServico gestao) {
        this.gestaoOrdemServico = gestao;
        initComponents();
        preencheComboBox();
        jLabel12.setVisible(false);
        jFTFDataCobranca.setVisible(false);
        jFTFDataCobranca1.setVisible(false);
        label3.setVisible(false);
        jLabel8.setVisible(false);
        jCBLote.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBSomenteUrgentes = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFNrOS = new javax.swing.JTextField();
        jTFNmCliente = new javax.swing.JTextField();
        jTFNmRua = new javax.swing.JTextField();
        jCBBairro = new javax.swing.JComboBox();
        jCBServicoAExecutar = new javax.swing.JComboBox();
        jCBStatus = new javax.swing.JComboBox();
        jCBEquipe = new javax.swing.JComboBox();
        jCBItemCobranca = new javax.swing.JComboBox();
        jCBLote = new javax.swing.JComboBox();
        label = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        jFTFDataEmissao = new javax.swing.JFormattedTextField();
        jFTFDataEmissao1 = new javax.swing.JFormattedTextField();
        jFTFDataInicio = new javax.swing.JFormattedTextField();
        jFTFDataInicio1 = new javax.swing.JFormattedTextField();
        jFTFDataFinal = new javax.swing.JFormattedTextField();
        jFTFDataFinal1 = new javax.swing.JFormattedTextField();
        jFTFDataCobranca = new javax.swing.JFormattedTextField();
        jFTFDataCobranca1 = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel1.setText("Número da OS:");

        jLabel2.setText("Serviços à executar:");

        jLabel3.setText("Rua:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Status:");

        jLabel7.setText("Equipe:");

        jCBSomenteUrgentes.setText("Somente Urgentes");

        jLabel8.setText("Lote:");

        jLabel9.setText("Data de emissão:");

        jLabel10.setText("Data de inicio da Execução:");

        jLabel11.setText("Data final da Execução:");

        jLabel13.setText("Cliente:");

        jLabel14.setText("Serviços de cobranças:");

        jCBLote.setEnabled(false);

        label.setText("à");

        label1.setText("à");

        label2.setText("à");

        jLabel12.setText("Data de cobrança:");

        label3.setText("à");

        try {
            jFTFDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataEmissao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataInicio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataFinal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFTFDataCobranca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFDataCobranca.setEnabled(false);

        try {
            jFTFDataCobranca1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFDataCobranca1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFNmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6))
                            .addComponent(jTFNmRua, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNrOS, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(83, 83, 83)
                        .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84)
                        .addComponent(jCBBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jCBServicoAExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(79, 79, 79)
                        .addComponent(jCBEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTFDataEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jFTFDataFinal)
                                    .addComponent(jFTFDataInicio)
                                    .addComponent(jFTFDataCobranca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label)
                                    .addComponent(label3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTFDataEmissao1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jFTFDataInicio1)
                                    .addComponent(jFTFDataFinal1)
                                    .addComponent(jFTFDataCobranca1)))
                            .addComponent(jCBItemCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBLote, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jCBSomenteUrgentes))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jCBSomenteUrgentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jCBItemCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(label2)
                            .addComponent(jFTFDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFDataEmissao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1)
                            .addComponent(jLabel10)
                            .addComponent(jFTFDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(label)
                            .addComponent(jFTFDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFDataFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3)
                            .addComponent(jFTFDataCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFDataCobranca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFNrOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jTFNmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jTFNmRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4))
                            .addComponent(jCBBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2))
                            .addComponent(jCBServicoAExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel5))
                                .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7))
                            .addComponent(jCBEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void preencheComboBox() {
        for (Status s : Status.values()) {
            jCBStatus.addItem(s.toString());
        }
        jCBStatus.setSelectedItem(null);

        for (Bairros b : Bairros.values()) {
            jCBBairro.addItem(b.toString());
        }
        jCBBairro.setSelectedItem(null);

        parametros.clear();
        parametros.put("DS_SERVICO", null);
        for (HashMap sae : new ServicosAExecutarDB().getServicosAExecutar(parametros, "DS_SERVICO")) {
            jCBServicoAExecutar.addItem(sae.get("DS_SERVICO"));
        }
        jCBServicoAExecutar.setSelectedItem(null);

        parametros.clear();
        parametros.put("NM_EQUIPE", null);

        for (HashMap equipe : new EquipeDB().getEquipes(parametros, "NM_EQUIPE")) {
            jCBEquipe.addItem(equipe.get("NM_EQUIPE"));
        }
        jCBEquipe.setSelectedItem(null);

        parametros.clear();
        parametros.put("DS_DESCRICAO", null);

        for (HashMap equipe : new ItemCobrancaDB().getItensCobranca(parametros, "DS_DESCRICAO")) {
            jCBItemCobranca.addItem(equipe.get("DS_DESCRICAO"));
        }
        jCBItemCobranca.setSelectedItem(null);
    }

    public HashMap montarRestricoes() {
        SimpleFormatter sf = new SimpleFormatter();
        HashMap restricoes = new HashMap();
        if (!jTFNrOS.getText().trim().equalsIgnoreCase("")) {
            restricoes.put("NR_ORDEM", UtilSql.prepararLike(jTFNrOS.getText(), true, false, false));
        }
        if (!jTFNmCliente.getText().trim().equalsIgnoreCase("")) {
            restricoes.put("NM_CLIENTE", UtilSql.prepararLike(jTFNmCliente.getText(), false, true, false));
        }
        if (!jTFNmRua.getText().trim().equalsIgnoreCase("")) {
            restricoes.put("NM_RUA", UtilSql.prepararLike(jTFNmRua.getText(), false, true, false));
        }
        if (jCBBairro.getSelectedItem() != null) {
            restricoes.put("NM_BAIRRO", UtilSql.aplicarApostofo(jCBBairro.getSelectedItem().toString()));
        }
        if (jCBServicoAExecutar.getSelectedItem() != null) {
            restricoes.put("SERVICO_A_EXECUTAR", UtilSql.aplicarApostofo(jCBServicoAExecutar.getSelectedItem().toString()));
        }
        if (jCBStatus.getSelectedItem() != null) {
            restricoes.put("STATUS_OS", UtilSql.aplicarApostofo(jCBStatus.getSelectedItem().toString()));
        }
        if (jCBItemCobranca.getSelectedItem() != null) {
            parametros.clear();
            parametros.put("ID", null);

            restricoesGeral.clear();
            restricoesGeral.put("DS_DESCRICAO", UtilSql.aplicarApostofo(jCBItemCobranca.getSelectedItem().toString()));

            retorno.clear();
            retorno = new ItemCobrancaDB().getItensCobranca(parametros, restricoesGeral, null);

            restricoes.put("PROCEDURE", new Procedures().ObterSeVinculoOSItemCobranca(retorno.get(0).get("ID").toString()));
        }

        if (jCBEquipe.getSelectedItem() != null) {
            parametros.clear();
            parametros.put("ID", null);

            restricoesGeral.clear();
            restricoesGeral.put("NM_EQUIPE", UtilSql.aplicarApostofo(jCBEquipe.getSelectedItem().toString()));

            retorno.clear();
            retorno = new EquipeDB().getEquipes(parametros, restricoesGeral, null);

            restricoes.put("NR_EQUIPE", retorno.get(0).get("ID"));
        }
        if (jCBLote.getSelectedItem() != null) {
            restricoes.put("NR_LOTE", jCBLote.getSelectedItem().toString());
        }
        if (!"  /  /    ".equalsIgnoreCase(jFTFDataEmissao.getText()) && Utilidades.getData(jFTFDataEmissao.getText()) != null) {
            if (Utilidades.getData(jFTFDataEmissao1.getText()) != null) {
                restricoes.put("DT_EMISSAO", UtilSql.preparaDataBetWeen(jFTFDataEmissao.getText(), jFTFDataEmissao1.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "É necessário possuir uma data de emissão inicial e final válidas");
            }

        }
        if (!"  /  /    ".equalsIgnoreCase(jFTFDataInicio.getText()) && Utilidades.getData(jFTFDataInicio.getText()) != null) {
            if (Utilidades.getData(jFTFDataInicio1.getText()) != null) {
                restricoes.put("DT_INICIAL", UtilSql.preparaDataBetWeen(jFTFDataInicio.getText(), jFTFDataInicio1.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "É necessário possuir uma data de execução inicial e final válidas");
            }
        }
        if (!"  /  /    ".equalsIgnoreCase(jFTFDataFinal.getText()) && Utilidades.getData(jFTFDataFinal.getText()) != null) {
            if (Utilidades.getData(jFTFDataFinal1.getText()) != null) {
                restricoes.put("DT_FINAL", UtilSql.preparaDataBetWeen(jFTFDataFinal.getText(), jFTFDataFinal1.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "É necessário possuir uma data de finalização inicial e final válidas");
            }
        }
        if (!"  /  /    ".equalsIgnoreCase(jFTFDataCobranca.getText()) && Utilidades.getData(jFTFDataCobranca.getText()) != null) {
            if (Utilidades.getData(jFTFDataCobranca1.getText()) != null) {
                restricoes.put("DT_COBRANCA", UtilSql.preparaDataBetWeen(jFTFDataCobranca.getText(), jFTFDataCobranca1.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "É necessário possuir uma data de cobrança inicial e final válidas");
            }
        }
        if (jCBSomenteUrgentes.isSelected()) {
            restricoes.put("IE_URGENCIA", "10");
        }
        return restricoes;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCBBairro;
    private javax.swing.JComboBox jCBEquipe;
    private javax.swing.JComboBox jCBItemCobranca;
    private javax.swing.JComboBox jCBLote;
    private javax.swing.JComboBox jCBServicoAExecutar;
    private javax.swing.JCheckBox jCBSomenteUrgentes;
    private javax.swing.JComboBox jCBStatus;
    private javax.swing.JFormattedTextField jFTFDataCobranca;
    private javax.swing.JFormattedTextField jFTFDataCobranca1;
    private javax.swing.JFormattedTextField jFTFDataEmissao;
    private javax.swing.JFormattedTextField jFTFDataEmissao1;
    private javax.swing.JFormattedTextField jFTFDataFinal;
    private javax.swing.JFormattedTextField jFTFDataFinal1;
    private javax.swing.JFormattedTextField jFTFDataInicio;
    private javax.swing.JFormattedTextField jFTFDataInicio1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTFNmCliente;
    private javax.swing.JTextField jTFNmRua;
    private javax.swing.JTextField jTFNrOS;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
