/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cadastro;

import ClassesDeConexao.EquipeDB;
import ClassesDeConexao.FuncionarioDB;
import JDLocalizadores.JDLocalizadorFuncionario;
import Model.Equipe;
import Model.Funcionario;
import Util.Utilidades;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import view.Gestao.GestaoEquipe;

/**
 *
 * @author csqueiroz
 */
public class CadastroEquipe extends javax.swing.JPanel {

    private Funcionario funcionario;
    private Equipe equipe;
    private GestaoEquipe gestaoEquipe;
    JDLocalizadorFuncionario lF = new JDLocalizadorFuncionario(this);

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroEquipe(GestaoEquipe gE) {
        gestaoEquipe = gE;
        initComponents();
    }

    private void cadastrarEquipe() {
        Equipe e;
        if (equipe != null) {
            e = new Equipe(equipe.getId(), funcionario.getID(), jTFNmEquipe.getText(), jTFNmCarro.getText(), jTFNrPlaca.getText());
        } else {
            e = new Equipe(0, funcionario.getID(), jTFNmEquipe.getText(), jTFNmCarro.getText(), jTFNrPlaca.getText());
        }

        if (new EquipeDB().criarEquipe(e)) {
            new Util.UtilPanel().limpaCampos(this);
            funcionario = null;
            equipe = null;
        }
    }

    public void setEquipe(Equipe e) {
        equipe = e;
        jTFNmCarro.setText(e.getNmCarro());
        jTFNmEquipe.setText(e.getNmEquipe());
        funcionario = new FuncionarioDB().getFuncionario(e.getNrFuncionario());
        jTFNmResponsavel.setText(funcionario.getNmFuncionario());
        jTFNrPlaca.setText(e.getNrPlaca());
    }

    private boolean validaCampos() {
        if (!jTFNmEquipe.getText().trim().equalsIgnoreCase("")) {
            if (!jTFNmResponsavel.getText().trim().equalsIgnoreCase("")) {
                if (!jTFNmCarro.getText().trim().equalsIgnoreCase("")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "É necessário possuir um nome do veículo.");
                    jTFNmCarro.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "É necessário possuir um responsável pela equipe.");
                jTFNmResponsavel.requestFocus();
            }
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "O nome da equipe é necessário.");
            jTFNmEquipe.requestFocus();
        }
        return false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNmEquipe = new javax.swing.JTextField();
        jTFNmResponsavel = new javax.swing.JTextField();
        jButtonCadastrar1 = new Botões.JButtonCadastrar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNmCarro = new javax.swing.JTextField();
        jTFNrPlaca = new javax.swing.JTextField();

        jLabel1.setText("Nome da equipe:");

        jLabel2.setText("Responsável:");
        jLabel2.setToolTipText("");

        jTFNmEquipe.setBackground(new java.awt.Color(153, 255, 255));
        jTFNmEquipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNmEquipeKeyPressed(evt);
            }
        });

        jTFNmResponsavel.setBackground(new java.awt.Color(153, 255, 255));
        jTFNmResponsavel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNmResponsavelKeyPressed(evt);
            }
        });

        jButtonCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Carro:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Placa:");
        jLabel4.setToolTipText("");

        jTFNmCarro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNmCarroKeyPressed(evt);
            }
        });

        jTFNrPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNrPlacaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTFNmCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addGap(421, 421, 421))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNmEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(jTFNmResponsavel))
                                .addGap(57, 57, 57)
                                .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFNrPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFNmEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFNmResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNrPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar1ActionPerformed
        verificador();
    }//GEN-LAST:event_jButtonCadastrar1ActionPerformed

    private void jTFNmEquipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNmEquipeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificador();
        }
    }//GEN-LAST:event_jTFNmEquipeKeyPressed

    private void jTFNmResponsavelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNmResponsavelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lF.ativar();
        } else {
            jTFNmResponsavel.setText("");
        }
    }//GEN-LAST:event_jTFNmResponsavelKeyPressed

    private void jTFNmCarroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNmCarroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificador();
        }
    }//GEN-LAST:event_jTFNmCarroKeyPressed

    private void jTFNrPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNrPlacaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificador();
        }
    }//GEN-LAST:event_jTFNrPlacaKeyPressed

    private void verificador() {
        if (validaCampos()) {
            cadastrarEquipe();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botões.JButtonCadastrar jButtonCadastrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFNmCarro;
    private javax.swing.JTextField jTFNmEquipe;
    private javax.swing.JTextField jTFNmResponsavel;
    private javax.swing.JTextField jTFNrPlaca;
    // End of variables declaration//GEN-END:variables

    public void atualizaRetorno() {
        funcionario = new FuncionarioDB().getFuncionario(new Utilidades().validaInt(lF.getRetorno()));
        jTFNmResponsavel.setText(funcionario.getNmFuncionario());
    }
}
