/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cadastro;

import ClassesDeConexao.ServicosAExecutarDB;
import Model.ServicosAExecutar;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author csqueiroz
 */
public class CadastroServicoAExecutar extends javax.swing.JPanel {

    ServicosAExecutar servicoAExecutar;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroServicoAExecutar() {
        initComponents();
    }

    public void setServicoAExecutar(ServicosAExecutar servicoAExecutar) {
        this.servicoAExecutar = servicoAExecutar;
        preencheCampos();
    }

    private void preencheCampos() {
        jTFDs_Descricao.setText(servicoAExecutar.getDsServico());
    }

    private void cadastrarServicoAExecutar() {
        if (servicoAExecutar != null) {
            ServicosAExecutar sae = new ServicosAExecutar(servicoAExecutar.getId(), jTFDs_Descricao.getText());
            if (new ServicosAExecutarDB().editarServicosAExecutar(sae)) {
                new Util.UtilPanel().limpaCampos(this);
                limpar();
                jTFDs_Descricao.requestFocus();
            }
        } else {
            ServicosAExecutar sae = new ServicosAExecutar(0, jTFDs_Descricao.getText());
            if (new ServicosAExecutarDB().cadastrarServicosAExecutar(sae)) {
                new Util.UtilPanel().limpaCampos(this);
                jTFDs_Descricao.requestFocus();
            }
        }

    }

    private boolean validaCampos() {
        if (!jTFDs_Descricao.getText().trim().equalsIgnoreCase("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "É necessário uma descrição do serviço.");
            jTFDs_Descricao.requestFocus();
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFDs_Descricao = new javax.swing.JTextField();
        jButtonCadastrar1 = new Botões.JButtonCadastrar();

        jLabel1.setText("Descrição:");

        jTFDs_Descricao.setBackground(new java.awt.Color(153, 255, 255));
        jTFDs_Descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDs_DescricaoKeyPressed(evt);
            }
        });

        jButtonCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jTFDs_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFDs_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar1ActionPerformed
        verificador();
    }//GEN-LAST:event_jButtonCadastrar1ActionPerformed

    private void jTFDs_DescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDs_DescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificador();
        }
    }//GEN-LAST:event_jTFDs_DescricaoKeyPressed

    private void verificador() {
        if (validaCampos()) {
            cadastrarServicoAExecutar();
        }
    }

    private void limpar() {
        servicoAExecutar = null;
        jTFDs_Descricao.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botões.JButtonCadastrar jButtonCadastrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFDs_Descricao;
    // End of variables declaration//GEN-END:variables
}
