/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cadastro;

import ClassesDeConexao.LicitacaoDB;
import JDLocalizadores.JDLocalizadorFuncionario;
import Model.Licitacao;
import Util.UtilPanel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import view.Gestao.GestaoLicitacao;

/**
 *
 * @author csqueiroz
 */
public class CadastroLicitacao extends javax.swing.JPanel {

    private Licitacao licitacao;
    private final GestaoLicitacao gestaoLicitacao;
    JDLocalizadorFuncionario lF = new JDLocalizadorFuncionario(this);

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroLicitacao(GestaoLicitacao gestaoLicitacao) {
        this.gestaoLicitacao = gestaoLicitacao;
        initComponents();
    }

    private void cadastrarLicitacao() {
        if (licitacao != null) {
            licitacao.setDsLicitacao(jTFNmLicitacao.getText());
            if (new LicitacaoDB().editarLicitacao(licitacao)) {
                UtilPanel.limpaCampos(this);
                licitacao = null;
                jTFNmLicitacao.requestFocus();
            }
        } else {
            licitacao = new Licitacao(0, jTFNmLicitacao.getText());

            if (new LicitacaoDB().cadastrarLicitacao(licitacao)) {
                UtilPanel.limpaCampos(this);
                licitacao = null;
            }
        }
    }

    private boolean validaCampos() {
        if (jTFNmLicitacao.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "É necessário possuir o nome da licitação.");
            jTFNmLicitacao.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFNmLicitacao = new javax.swing.JTextField();
        jButtonCadastrar1 = new Botões.JButtonCadastrar();

        jLabel1.setText("Nome do contrato:");

        jTFNmLicitacao.setBackground(new java.awt.Color(153, 255, 255));
        jTFNmLicitacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNmLicitacaoKeyPressed(evt);
            }
        });

        jButtonCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNmLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNmLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar1ActionPerformed
        verificador();
    }//GEN-LAST:event_jButtonCadastrar1ActionPerformed

    private void jTFNmLicitacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNmLicitacaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificador();
        }
    }//GEN-LAST:event_jTFNmLicitacaoKeyPressed

    private void verificador() {
        if (validaCampos()) {
            cadastrarLicitacao();
        }
    }

    public void setLicitacao(Licitacao licitacao) {
        jTFNmLicitacao.setText(licitacao.getDsLicitacao());
        this.licitacao = licitacao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botões.JButtonCadastrar jButtonCadastrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTFNmLicitacao;
    // End of variables declaration//GEN-END:variables

}
