/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cadastro;

import ClassesDeConexao.RelatorioDB;
import Contantes.NomesColunasContantes;
import JTPadrao.JCTable;
import Model.Relatorio;
import Util.UtilPanel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.SwingUtilities;

/**
 *
 * @author csqueiroz
 */
public class CadastroDeRelatorios extends javax.swing.JPanel {

    private final String from = "from TB_OS os left join TB_EQUIPE equipe on os.NR_EQUIPE = equipe.ID inner join TB_LICITACAO licitacao on os.CD_LICITACAO = licitacao.ID";
    private ArrayList<HashMap> camposRelatorio = new ArrayList<HashMap>();

    /**
     * Creates new form GestaoDeRelatorios
     */
    public CadastroDeRelatorios() {
        initComponents();
        carregarComboboxTabelas();
        jCBOrientacao.addItem("Retrato");
        jCBOrientacao.addItem("Paisagem");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBOrientacao = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jButtonSalvar1 = new Botões.JButtonSalvar();
        camposJCB = new javax.swing.JComboBox();
        sizeJTF = new javax.swing.JTextField();
        sequenciaJTF = new javax.swing.JTextField();
        jButtonIncluir = new Botões.JButtonIncluir();
        jButtonRemover = new Botões.JButtonRemover();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCTCampos = new JTPadrao.JCTable();

        jLabel3.setText("jLabel3");

        jLabel4.setText("Orientação:");

        jLabel13.setText("Nome do relatório:");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });

        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabel6.setText("Campo:");

        jLabel7.setText("Tamanho da coluna:");

        jLabel8.setText("Sequencia de apresentação:");

        jCTCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jCTCampos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 680, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(camposJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sizeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sequenciaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(camposJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sequenciaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        HashMap campoRelatorio = new HashMap();
        //campoRelatorio.put("ATRIBUTO", getCampos().get(camposJCB.getSelectedItem().toString()));
        campoRelatorio.put("ATRIBUTO", camposJCB.getSelectedItem().toString());
        campoRelatorio.put("SIZE", sizeJTF.getText());
        campoRelatorio.put("ORDER", sequenciaJTF.getText());
        camposRelatorio.add(campoRelatorio);
        atualizaTable();

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        atualizaTable();
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        salvar();
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void carregarComboboxTabelas() {
        HashMap campos = getCampos();
        for (int x = 0; x < campos.keySet().toArray().length; x++) {
            camposJCB.addItem(campos.keySet().toArray()[x]);
        }
    }

    private void salvar() {
        Relatorio relatorio = new Relatorio();
        relatorio.setNmRelatorio(jTFNome.getText());
        relatorio.setOrientacao(jCBOrientacao.getSelectedItem().toString());
        for (HashMap hm : camposRelatorio) {
            hm.replace("ATRIBUTO", getCampos().get(hm.get("ATRIBUTO")).toString());
        }
        relatorio.setAtributos(camposRelatorio);
        new RelatorioDB().criarRelatorio(relatorio);
        UtilPanel.limpaCampos(this);
        atualizaTable();
    }

    private void atualizaTable() {
        jCTCampos = new JCTable(camposRelatorio, new NomesColunasContantes().getNomesColunas());
        jScrollPane2.setViewportView(jCTCampos);
        jCTCampos.validate();
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                jCTCampos.repaint();
            }
        });
    }

    private HashMap getCampos() {
        HashMap campos = new HashMap();
        campos.put("Número da OS", "os.NR_ORDEM,");
        campos.put("Data de emissão", "os.DT_EMISSAO,");
        campos.put("Nome do cliente", "os.NM_CLIENTE,");
        campos.put("Nome da rua", "os.NM_RUA,");
        campos.put("Número da rua", "os.NUMERO,");
        campos.put("Complemento", "os.COMPL_CLIENTE,");
        campos.put("Telefone do cliente", "os.NR_TELEFONE,");
        campos.put("Bairro", "os.NM_BAIRRO,");
        campos.put("Serviço a executar", "os.SERVICO_A_EXECUTAR,");
        campos.put("Código da rua", "os.COD_RUA,");

        campos.put("Código do setor", "os.COD_SETOR,");
        campos.put("Número do hidrometro", "os.NR_HIDROMETRO,");
        campos.put("Status da OS", "os.STATUS_OS,");

        campos.put("Bairro", "os.NM_BAIRRO,");
        campos.put("Data inicial", "os.DT_INICIAL,");
        campos.put("Data final", "os.DT_FINAL,");

        campos.put("Observação da execução", "os.DS_OBSERVACAO,");
        campos.put("Equipe", "equipe.NM_EQUIPE,");
        campos.put("Data de cobrança", "os.DT_COBRANCA,");
        campos.put("Referência", "os.REFERENCIA,");
        campos.put("Urgência", "if(os.IE_URGENTE=10,'Sim','Não') urgencia,");
        campos.put("Número do lote", "os.NR_LOTE,");
        campos.put("Contrato", "if(os.CD_LICITACAO=null,'',licitacao.DS_LICITACAO) DS_LICITACAO,");

        return campos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox camposJCB;
    private Botões.JButtonIncluir jButtonIncluir;
    private Botões.JButtonRemover jButtonRemover;
    private Botões.JButtonSalvar jButtonSalvar1;
    private javax.swing.JComboBox jCBOrientacao;
    private JTPadrao.JCTable jCTCampos;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField sequenciaJTF;
    private javax.swing.JTextField sizeJTF;
    // End of variables declaration//GEN-END:variables
}
