/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gestao;

import Util.UtilPanel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import view.Filtro.FiltroRelatorio;

/**
 *
 * @author csqueiroz
 */
public class GestaoRelatorio extends javax.swing.JPanel {

    /**
     * Creates new form GestaoOrdemServico
     */
    public GestaoRelatorio() {
        initComponents();
        this.add(new FiltroRelatorio(this));
        //alteraPainelNorte(new FiltroRelatorio(this));
        //alteraPainelSouth(new PanelGestaoOrdemDeServico(this));

    }

    public void alteraPainelNorte(JPanel panel) {
        jPNorth = panel;
        this.repaint();
        jPNorth.repaint();
    }

    public JPanel getPanelNorth() {
        return this.jPNorth;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jPNorth = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1024, 800));
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPNorthLayout = new javax.swing.GroupLayout(jPNorth);
        jPNorth.setLayout(jPNorthLayout);
        jPNorthLayout.setHorizontalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPNorthLayout.setVerticalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(jPNorth, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPNorth;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables
}
