/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gestao;

import ClassesDeConexao.UsuarioDB;
import Model.Status;
import java.util.HashMap;

/**
 *
 * @author csqueiroz
 */
public class GestaoDePermissoes extends javax.swing.JPanel {

    /**
     * Creates new form GestaoDePermissoes
     */
    public GestaoDePermissoes() {
        initComponents();
        preencheComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox4 = new javax.swing.JCheckBox();
        jCBGestaoDeFuncionario = new javax.swing.JCheckBox();
        jCBCadastrarFuncionario = new javax.swing.JCheckBox();
        jCBAlterarFuncionario = new javax.swing.JCheckBox();
        jCBExcluirFuncionario = new javax.swing.JCheckBox();
        jCBCadastrarUsuario = new javax.swing.JCheckBox();
        jCBAlterarUsuario = new javax.swing.JCheckBox();
        jCBExcluirUsuario = new javax.swing.JCheckBox();
        jCBGestaoDeUsuario = new javax.swing.JCheckBox();
        jCBExcluirEquipe = new javax.swing.JCheckBox();
        jCBAlterarEquipe = new javax.swing.JCheckBox();
        jCBCadastrarEquipe = new javax.swing.JCheckBox();
        jCBGestaoDeEquipes = new javax.swing.JCheckBox();
        jCBCadastrarServicosAExecutar = new javax.swing.JCheckBox();
        jCBGestaoDeServicosAExecutar = new javax.swing.JCheckBox();
        jCBAlterarServicosAExecutar = new javax.swing.JCheckBox();
        jCBExcluirServicosAExecutar = new javax.swing.JCheckBox();
        jCBGestaoDeItemDeCobranca = new javax.swing.JCheckBox();
        jCBCadastrarItemDeCobranca = new javax.swing.JCheckBox();
        jCBAlterarItemDeCobranca = new javax.swing.JCheckBox();
        jCBExcluirItemDeCobranca = new javax.swing.JCheckBox();
        jCBGestaoDeOrdemDeServico = new javax.swing.JCheckBox();
        jCBCadastrarOS = new javax.swing.JCheckBox();
        jCBExecutarOS = new javax.swing.JCheckBox();
        jCBFinalizarOS = new javax.swing.JCheckBox();
        jCBCobrarOS = new javax.swing.JCheckBox();
        jCBCancelar = new javax.swing.JCheckBox();
        jCBAlterarOS = new javax.swing.JCheckBox();
        jCBAlterarStatusOS = new javax.swing.JCheckBox();
        jCBVisualizarOS = new javax.swing.JCheckBox();
        jCBGestaoDeRelatorios = new javax.swing.JCheckBox();
        jCBCadastrarRelatorio = new javax.swing.JCheckBox();
        jCBAlterarRelatorio = new javax.swing.JCheckBox();
        jCBExcluirRelatorio = new javax.swing.JCheckBox();
        jCBUsuarios = new javax.swing.JComboBox();
        jButtonCadastrar1 = new Botões.JButtonCadastrar();

        jCheckBox4.setText("jCheckBox4");

        jCBGestaoDeFuncionario.setText("Gestão de funcionários");

        jCBCadastrarFuncionario.setText("Cadastrar");
        jCBCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jCBAlterarFuncionario.setText("Alterar");

        jCBExcluirFuncionario.setText("Excluir");

        jCBCadastrarUsuario.setText("Cadastrar");

        jCBAlterarUsuario.setText("Alterar");

        jCBExcluirUsuario.setText("Excluir");

        jCBGestaoDeUsuario.setText("Gestão de Usuários");

        jCBExcluirEquipe.setText("Excluir");

        jCBAlterarEquipe.setText("Alterar");

        jCBCadastrarEquipe.setText("Cadastrar");

        jCBGestaoDeEquipes.setText("Gestão de Equipes");

        jCBCadastrarServicosAExecutar.setText("Cadastrar");

        jCBGestaoDeServicosAExecutar.setText("Gestão de Serviços à Executar");

        jCBAlterarServicosAExecutar.setText("Alterar");

        jCBExcluirServicosAExecutar.setText("Excluir");

        jCBGestaoDeItemDeCobranca.setText("Gestão de Itens de Cobrança");

        jCBCadastrarItemDeCobranca.setText("Cadastrar");

        jCBAlterarItemDeCobranca.setText("Alterar");

        jCBExcluirItemDeCobranca.setText("Excluir");

        jCBGestaoDeOrdemDeServico.setText("Gestão de Ordem de Serviço");

        jCBCadastrarOS.setText("Cadastrar");

        jCBExecutarOS.setText("Executar");

        jCBFinalizarOS.setText("Finalizar");

        jCBCobrarOS.setText("Cobrar");

        jCBCancelar.setText("Cancelar");

        jCBAlterarOS.setText("Alterar");

        jCBAlterarStatusOS.setText("Alterar Status");

        jCBVisualizarOS.setText("Visualizar");

        jCBGestaoDeRelatorios.setText("Gestão de Relátorios");

        jCBCadastrarRelatorio.setText("Cadastrar");

        jCBAlterarRelatorio.setText("Alterar");

        jCBExcluirRelatorio.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jCBAlterarUsuario)
                        .addGap(53, 53, 53)
                        .addComponent(jCBExcluirUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBGestaoDeEquipes)
                            .addComponent(jCBGestaoDeServicosAExecutar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(jCBAlterarEquipe)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBExcluirEquipe))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jCBCadastrarServicosAExecutar)
                                        .addGap(50, 50, 50)
                                        .addComponent(jCBAlterarServicosAExecutar)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBExcluirServicosAExecutar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBCadastrarItemDeCobranca)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBAlterarItemDeCobranca)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBExcluirItemDeCobranca))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBCadastrarOS)
                                            .addComponent(jCBCobrarOS)
                                            .addComponent(jCBAlterarStatusOS))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBExecutarOS)
                                            .addComponent(jCBCancelar)
                                            .addComponent(jCBVisualizarOS))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBAlterarOS)
                                            .addComponent(jCBFinalizarOS)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBCadastrarRelatorio)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBAlterarRelatorio)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBExcluirRelatorio))))
                            .addComponent(jCBGestaoDeItemDeCobranca)
                            .addComponent(jCBGestaoDeOrdemDeServico)
                            .addComponent(jCBGestaoDeRelatorios)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCBCadastrarFuncionario)
                                        .addComponent(jCBGestaoDeUsuario)
                                        .addComponent(jCBCadastrarUsuario)
                                        .addComponent(jCBCadastrarEquipe))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCBUsuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCBGestaoDeFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBAlterarFuncionario)
                                        .addGap(53, 53, 53)
                                        .addComponent(jCBExcluirFuncionario))
                                    .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(22, 22, 22)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jCBGestaoDeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarFuncionario)
                    .addComponent(jCBAlterarFuncionario)
                    .addComponent(jCBExcluirFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarUsuario)
                    .addComponent(jCBAlterarUsuario)
                    .addComponent(jCBExcluirUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeEquipes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarEquipe)
                    .addComponent(jCBAlterarEquipe)
                    .addComponent(jCBExcluirEquipe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeServicosAExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarServicosAExecutar)
                    .addComponent(jCBAlterarServicosAExecutar)
                    .addComponent(jCBExcluirServicosAExecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeItemDeCobranca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarItemDeCobranca)
                    .addComponent(jCBAlterarItemDeCobranca)
                    .addComponent(jCBExcluirItemDeCobranca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarRelatorio)
                    .addComponent(jCBAlterarRelatorio)
                    .addComponent(jCBExcluirRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBGestaoDeOrdemDeServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCadastrarOS)
                    .addComponent(jCBExecutarOS)
                    .addComponent(jCBFinalizarOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCobrarOS)
                    .addComponent(jCBCancelar)
                    .addComponent(jCBAlterarOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAlterarStatusOS)
                    .addComponent(jCBVisualizarOS))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCadastrarFuncionarioActionPerformed

    private void preencheComboBox(){
        HashMap parametros = new HashMap();
        parametros.put("NM_USUARIO", null);
        for (HashMap hm : new UsuarioDB().getUsuarios(parametros, "NM_USUARIO")) {
            jCBUsuarios.addItem(hm.get("NM_USUARIO"));
        }
        jCBUsuarios.setSelectedItem(null);
    }
    
    private void preencheChechboxes(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botões.JButtonCadastrar jButtonCadastrar1;
    private javax.swing.JCheckBox jCBAlterarEquipe;
    private javax.swing.JCheckBox jCBAlterarFuncionario;
    private javax.swing.JCheckBox jCBAlterarItemDeCobranca;
    private javax.swing.JCheckBox jCBAlterarOS;
    private javax.swing.JCheckBox jCBAlterarRelatorio;
    private javax.swing.JCheckBox jCBAlterarServicosAExecutar;
    private javax.swing.JCheckBox jCBAlterarStatusOS;
    private javax.swing.JCheckBox jCBAlterarUsuario;
    private javax.swing.JCheckBox jCBCadastrarEquipe;
    private javax.swing.JCheckBox jCBCadastrarFuncionario;
    private javax.swing.JCheckBox jCBCadastrarItemDeCobranca;
    private javax.swing.JCheckBox jCBCadastrarOS;
    private javax.swing.JCheckBox jCBCadastrarRelatorio;
    private javax.swing.JCheckBox jCBCadastrarServicosAExecutar;
    private javax.swing.JCheckBox jCBCadastrarUsuario;
    private javax.swing.JCheckBox jCBCancelar;
    private javax.swing.JCheckBox jCBCobrarOS;
    private javax.swing.JCheckBox jCBExcluirEquipe;
    private javax.swing.JCheckBox jCBExcluirFuncionario;
    private javax.swing.JCheckBox jCBExcluirItemDeCobranca;
    private javax.swing.JCheckBox jCBExcluirRelatorio;
    private javax.swing.JCheckBox jCBExcluirServicosAExecutar;
    private javax.swing.JCheckBox jCBExcluirUsuario;
    private javax.swing.JCheckBox jCBExecutarOS;
    private javax.swing.JCheckBox jCBFinalizarOS;
    private javax.swing.JCheckBox jCBGestaoDeEquipes;
    private javax.swing.JCheckBox jCBGestaoDeFuncionario;
    private javax.swing.JCheckBox jCBGestaoDeItemDeCobranca;
    private javax.swing.JCheckBox jCBGestaoDeOrdemDeServico;
    private javax.swing.JCheckBox jCBGestaoDeRelatorios;
    private javax.swing.JCheckBox jCBGestaoDeServicosAExecutar;
    private javax.swing.JCheckBox jCBGestaoDeUsuario;
    private javax.swing.JComboBox jCBUsuarios;
    private javax.swing.JCheckBox jCBVisualizarOS;
    private javax.swing.JCheckBox jCheckBox4;
    // End of variables declaration//GEN-END:variables
}
