/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gestao;

import ClassesDeConexao.GeralDB;
import Contantes.NomesColunasContantes;
import JTPadrao.JCTable;

/**
 *
 * @author csqueiroz
 */
public class GestaoDeParametros extends javax.swing.JPanel {

    /**
     * Creates new form GestaoDeParametros
     */
    public GestaoDeParametros() {
        initComponents();
        carregarFuncoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPListaFuncoes = new javax.swing.JScrollPane();
        jTFuncoes = new javax.swing.JTable();
        jSPListaParametros = new javax.swing.JScrollPane();
        jtParametros = new javax.swing.JTable();
        jSPEstabelecimento = new javax.swing.JScrollPane();
        jTPreferenciaEstabelecimento = new javax.swing.JTable();
        jSPListaUsuarios = new javax.swing.JScrollPane();
        jtListausuarios = new javax.swing.JTable();

        jTFuncoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jSPListaFuncoes.setViewportView(jTFuncoes);

        jtParametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPListaParametros.setViewportView(jtParametros);

        jTPreferenciaEstabelecimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPEstabelecimento.setViewportView(jTPreferenciaEstabelecimento);

        jtListausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSPListaUsuarios.setViewportView(jtListausuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPListaFuncoes, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPListaParametros, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(jSPEstabelecimento)
                    .addComponent(jSPListaUsuarios))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPListaFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSPListaParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carregarFuncoes(){
        jTFuncoes = new JCTable(new GeralDB().getFuncoes(), new NomesColunasContantes().getNomesColunas());
        jSPListaFuncoes.setViewportView(jTFuncoes);
        jTFuncoes.validate();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSPEstabelecimento;
    private javax.swing.JScrollPane jSPListaFuncoes;
    private javax.swing.JScrollPane jSPListaParametros;
    private javax.swing.JScrollPane jSPListaUsuarios;
    private javax.swing.JTable jTFuncoes;
    private javax.swing.JTable jTPreferenciaEstabelecimento;
    private javax.swing.JTable jtListausuarios;
    private javax.swing.JTable jtParametros;
    // End of variables declaration//GEN-END:variables
}
