/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gestao;

import javax.swing.JPanel;
import view.Cadastro.CadastroFuncionario;
import view.Edicao.EdicaoFuncionario;

/**
 *
 * @author csqueiroz
 */
public class GestaoFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form GestaoUsuario
     */
    public GestaoFuncionario() {
        initComponents();
        alteraPainelNorte(new CadastroFuncionario());
        alteraPainelSouth(new EdicaoFuncionario(this));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPNorth = new javax.swing.JPanel();
        jPSouth = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPNorth.setPreferredSize(new java.awt.Dimension(798, 150));

        javax.swing.GroupLayout jPNorthLayout = new javax.swing.GroupLayout(jPNorth);
        jPNorth.setLayout(jPNorthLayout);
        jPNorthLayout.setHorizontalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPNorthLayout.setVerticalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPNorth);

        jPSouth.setPreferredSize(new java.awt.Dimension(796, 550));

        javax.swing.GroupLayout jPSouthLayout = new javax.swing.GroupLayout(jPSouth);
        jPSouth.setLayout(jPSouthLayout);
        jPSouthLayout.setHorizontalGroup(
            jPSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPSouthLayout.setVerticalGroup(
            jPSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPSouth);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void alteraPainelNorte(JPanel panel) {
        jPNorth = panel;
        jSplitPane1.setLeftComponent(panel);
    }

    public void alteraPainelSouth(JPanel panel) {
        jPSouth = panel;
        jSplitPane1.setRightComponent(panel);
    }

    public JPanel getPanelNorte() {
        return jPNorth;
    }

    public JPanel getPanelSul() {
        return jPSouth;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPNorth;
    private javax.swing.JPanel jPSouth;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
