/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Gestao;

import Util.UtilPanel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import view.Filtro.FiltroGestaoOrdemServico;
import view.JPUM.GestaoOrdemDeServicoPUM;

/**
 *
 * @author csqueiroz
 */
public class GestaoOrdemServico extends javax.swing.JPanel {

    private GestaoOrdemDeServicoPUM gestaoOSPUM;

    /**
     * Creates new form GestaoOrdemServico
     */
    public GestaoOrdemServico() {
        initComponents();

        alteraPainelNorte(new FiltroGestaoOrdemServico(this));
        alteraPainelSouth(new PanelGestaoOrdemDeServico(this));
        gestaoOSPUM = new GestaoOrdemDeServicoPUM(this);
        this.addActions();
        
    }

    public void alteraPainelNorte(JPanel panel) {
        jPNorth = panel;
        jSplitPane1.setLeftComponent(panel);
    }

    public void alteraPainelSouth(JPanel panel) {
        jPSouth = panel;
        jSplitPane1.setRightComponent(panel);
    }

    public JPanel getPanelSouth() {
        return this.jPSouth;
    }

    public JPanel getPanelNorth() {
        return this.jPNorth;
    }

    private void addActions() {
        UtilPanel.adicionarMouseListener(this, getMouseListener());
        UtilPanel.adicionarKeyListener(this, getKeyListener());

    }

    public MouseListener getMouseListener() {
        return new MouseAdapter() {
            public void mouseReleased(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON3) {
                    gestaoOSPUM.verificarMenus();
                    gestaoOSPUM.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        };
    }

    public KeyListener getKeyListener() {
        return new KeyListener() {

            @Override
            public void keyTyped(KeyEvent evt) {

            }

            @Override
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_F1) {
                    ((PanelGestaoOrdemDeServico) getPanelSouth()).cadastrarOrdem();
                }
                if (evt.getKeyCode() == KeyEvent.VK_F5) {
                    ((PanelGestaoOrdemDeServico) getPanelSouth()).atualizarConsulta(((FiltroGestaoOrdemServico) getPanelNorth()).montarRestricoes());
                }
                if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    if (evt.getComponent() instanceof JComboBox) {
                        ((JComboBox) evt.getComponent()).setSelectedItem(null);
                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent evt) {
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPNorth = new javax.swing.JPanel();
        jPSouth = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1024, 800));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPNorthLayout = new javax.swing.GroupLayout(jPNorth);
        jPNorth.setLayout(jPNorthLayout);
        jPNorthLayout.setHorizontalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        jPNorthLayout.setVerticalGroup(
            jPNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPNorth);

        javax.swing.GroupLayout jPSouthLayout = new javax.swing.GroupLayout(jPSouth);
        jPSouth.setLayout(jPSouthLayout);
        jPSouthLayout.setHorizontalGroup(
            jPSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        jPSouthLayout.setVerticalGroup(
            jPSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPSouth);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPNorth;
    private javax.swing.JPanel jPSouth;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
