package Model;

public  enum Bairros {
	AGUA_VERDE,ASILO,BADENFURT,BOA_VISTA,BOM_RETIRO,CENTRO,ESCOLA_AGRICOLA,FIDELIS,FORTALEZA,FORTALEZA_ALTA,GARCIA,GLORIA,GRANDE_GARCIA,ITOUPAVA_CENTRAL,ITOUPAVA_NORTE,ITOUPAVA_SECA,ITOUPAVAZINHA,JARDIM_BLUMENAU,NOVA_ESPERANCA,PASSO_MANSO,PONTA_AGUDA,PROGRESSO,RIBERAO_FRESCO,SALTO,SALTO_DO_NORTE,SALTO_WEISSBACH,TESTO_SALTO,TRIBESS,VALPARAISO,VELHA,VELHA_CENTRAL,VELHA_GRANDE,VICTOR_KONDER,VILA_FORMOSA,VILA_ITOUPAVA,VILA_NOVA,VORSTADT;
}
