/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Usuario;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import view.MenuBar.MainFrameBar;

/**
 *
 * @author csqueiroz
 */
public class MainFrameSLM extends javax.swing.JFrame {

    public static MainFrameSLM mainFrameSLM;
    private Usuario usuario;

    public static MainFrameSLM getInstance() {
        if (mainFrameSLM == null) {
            mainFrameSLM = new MainFrameSLM();
        }
        return mainFrameSLM;
    }

    /**
     * Creates new form MainFrame
     */
    private MainFrameSLM() {

        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/SLMLogoICon.png")));
        this.setTitle("SLM Construções");
        this.setSize(1080,764);
        setLocationRelativeTo(null);
        statusBar1.setVersion("2.0");
        jTabbedPaneComponentRemoved(null);
        ativar();
    }

    public StatusBar getStatusBar() {
        return this.statusBar1;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario u) {
        this.usuario = u;
        statusBar1.setUsuario(u.getNmUsuario());
    }

    public void ativar() {
        jMBMainFrame.removeAll();
        jMBMainFrame.add(new MainFrameBar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusBar1 = new view.StatusBar();
        jTabbedPane = new ComponentesVisuais.ClosableTabbedPane();
        jMBMainFrame = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(statusBar1, java.awt.BorderLayout.SOUTH);

        jTabbedPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTabbedPaneComponentRemoved(evt);
            }
        });
        getContentPane().add(jTabbedPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMBMainFrame.add(jMenu1);

        jMenu2.setText("Edit");
        jMBMainFrame.add(jMenu2);

        setJMenuBar(jMBMainFrame);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTabbedPaneComponentRemoved
        if (jTabbedPane.getTabCount() == 0) {
            adicionarAba(new mainPanel(), "Painel principal");
        }
    }//GEN-LAST:event_jTabbedPaneComponentRemoved

    /**
     * @param args the command line arguments
     */
    public void adicionarAba(JPanel aba, String titulo) {
        this.jTabbedPane.addTab(titulo, aba);
        this.jTabbedPane.setSelectedComponent(aba);

    }

    public void fecharAba(JPanel aba) {
        this.jTabbedPane.remove(aba);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMBMainFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private ComponentesVisuais.ClosableTabbedPane jTabbedPane;
    private view.StatusBar statusBar1;
    // End of variables declaration//GEN-END:variables
}
